// Generated by wxt
export {}
declare global {
  const ButtonInput: typeof import('/Users/qliang/Sync/code/Auths/src/components/common/index').ButtonInput
  const ButtonLink: typeof import('/Users/qliang/Sync/code/Auths/src/components/common/index').ButtonLink
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const EntryComponent: typeof import('/Users/qliang/Sync/code/Auths/src/components/Popup/index').EntryComponent
  const FileInput: typeof import('/Users/qliang/Sync/code/Auths/src/components/common/index').FileInput
  const Import: typeof import('/Users/qliang/Sync/code/Auths/src/components/index').Import
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MainBody: typeof import('/Users/qliang/Sync/code/Auths/src/components/Popup/index').MainBody
  const MainHeader: typeof import('/Users/qliang/Sync/code/Auths/src/components/Popup/index').MainHeader
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const MenuPage: typeof import('/Users/qliang/Sync/code/Auths/src/components/Popup/index').MenuPage
  const NotificationHandler: typeof import('/Users/qliang/Sync/code/Auths/src/components/Popup/index').NotificationHandler
  const Options: typeof import('/Users/qliang/Sync/code/Auths/src/components/index').Options
  const PageHandler: typeof import('/Users/qliang/Sync/code/Auths/src/components/Popup/index').PageHandler
  const Permissions: typeof import('/Users/qliang/Sync/code/Auths/src/components/index').Permissions
  const Popup: typeof import('/Users/qliang/Sync/code/Auths/src/components/Popup/index').Popup
  const SelectInput: typeof import('/Users/qliang/Sync/code/Auths/src/components/common/index').SelectInput
  const TextInput: typeof import('/Users/qliang/Sync/code/Auths/src/components/common/index').TextInput
  const ToggleInput: typeof import('/Users/qliang/Sync/code/Auths/src/components/common/index').ToggleInput
  const browser: typeof import('wxt/browser').browser
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const decryptBackupData: typeof import('/Users/qliang/Sync/code/Auths/src/utils/import').decryptBackupData
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const getCachedSecrets: typeof import('/Users/qliang/Sync/code/Auths/src/utils/import').getCachedSecrets
  const getEntryDataFromOTPAuthPerLine: typeof import('/Users/qliang/Sync/code/Auths/src/utils/import').getEntryDataFromOTPAuthPerLine
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const storage: typeof import('wxt/utils/storage').storage
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useEffect: typeof import('react').useEffect
  const useMemo: typeof import('react').useMemo
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
}
