// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/_locales/zh_CN/messages.json"
    | "/background.js"
    | "/content-scripts/region-selector.js"
    | "/images/icon.svg"
    | "/images/icon128.png"
    | "/images/icon16.png"
    | "/images/icon19.png"
    | "/images/icon38.png"
    | "/images/icon48.png"
    | "/images/scan.gif"
    | "/import.html"
    | "/options.html"
    | "/permissions.html"
    | "/popup.html"
    | "/svg/arrow-left.svg"
    | "/svg/bars.svg"
    | "/svg/check.svg"
    | "/svg/clipboard-check.svg"
    | "/svg/code.svg"
    | "/svg/cog.svg"
    | "/svg/comments.svg"
    | "/svg/database.svg"
    | "/svg/exchange.svg"
    | "/svg/globe.svg"
    | "/svg/info.svg"
    | "/svg/key-solid.svg"
    | "/svg/lightbulb.svg"
    | "/svg/lock.svg"
    | "/svg/minus-circle.svg"
    | "/svg/pencil.svg"
    | "/svg/pin.svg"
    | "/svg/plus.svg"
    | "/svg/qrcode.svg"
    | "/svg/redo.svg"
    | "/svg/scan.svg"
    | "/svg/sync.svg"
    | "/svg/wrench.svg"
    | "/svg/x-circle.svg"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
